[View in Colaboratory](https://colab.research.google.com/github/minhthien/dog-breed-classification/blob/master/dog_breed_classification.ipynb)

In [1]:
!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse

Preconfiguring packages ...
Selecting previously unselected package cron.
(Reading database ... 18298 files and directories currently installed.)
Preparing to unpack .../00-cron_3.0pl1-128ubuntu5_amd64.deb ...
Unpacking cron (3.0pl1-128ubuntu5) ...
Selecting previously unselected package libapparmor1:amd64.
Preparing to unpack .../01-libapparmor1_2.11.0-2ubuntu17.1_amd64.deb ...
Unpacking libapparmor1:amd64 (2.11.0-2ubuntu17.1) ...
Selecting previously unselected package libdbus-1-3:amd64.
Preparing to unpack .../02-libdbus-1-3_1.10.22-1ubuntu1_amd64.deb ...
Unpacking libdbus-1-3:amd64 (1.10.22-1ubuntu1) ...
Selecting previously unselected package dbus.
Preparing to unpack .../03-dbus_1.10.22-1ubuntu1_amd64.deb ...
Unpacking dbus (1.10.22-1ubuntu1) ...
Selecting previously unselected package dirmngr.
Preparing to unpack .../04-dirmngr_2.1.15-1ubuntu8_amd64.deb ...
Unpacking dirmngr (2.1.15-1ubuntu8) ...
Selecting previously unselected package distro-info-data.
Preparing to unpack .../0


Creating config file /etc/apt/apt.conf.d/20auto-upgrades with new version

Creating config file /etc/apt/apt.conf.d/50unattended-upgrades with new version
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Setting up dirmngr (2.1.15-1ubuntu8) ...
Setting up cron (3.0pl1-128ubuntu5) ...
Adding group `crontab' (GID 102) ...
Done.
update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
update-rc.d: warning: stop runlevel arguments (1) do not match cron Default-Stop values (none)
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Setting up libdbus-1-3:amd64 (1.10.22-1ubuntu1) ...
Setting up kmod (24-1ubuntu2) ...
Setting up libdbus-glib-1-2:amd64 (0.108-2) ...
Setting up python3-gi (3.24.1-2build1) ...
Setting up module-init-tools (24-1ubuntu2) ...
Setting up python3-software-properties (0.96.24.17) ...
Setting up dbus (1.10.22-1ubuntu1) ...
Setting

In [0]:
from google.colab import auth
auth.authenticate_user()

In [6]:
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()
import getpass
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}

Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=32555940559.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force
··········
Please, open the following URL in a web browser: https://accounts.google.com/o/oauth2/auth?client_id=32555940559.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&response_type=code&access_type=offline&approval_prompt=force
Please enter the verification code: Access token retrieved correctly.


In [0]:
!mkdir -p My Drive
!google-drive-ocamlfuse My Drive

Reading all the prepared data from google drive

In [0]:
import numpy as np
x_train = np.load('Drive/dog_breed_resources/ready_data/dog_breed_ready/dog_breed_ready/xtrain.npy')
y_train = np.load('Drive/dog_breed_resources/ready_data/dog_breed_ready/dog_breed_ready/ytrain.npy')
x_val = np.load('Drive/dog_breed_resources/ready_data/dog_breed_ready/dog_breed_ready/xval.npy')
y_val = np.load('Drive/dog_breed_resources/ready_data/dog_breed_ready/dog_breed_ready/yval.npy')
x_test_data = np.load('Drive/dog_breed_resources/ready_data/dog_breed_ready/dog_breed_ready/xtestdata.npy')
one_hot_encode_label = np.load('Drive/dog_breed_resources/ready_data/dog_breed_ready/dog_breed_ready/one_hot_encode_label.npy')
test_image_ids = np.load('Drive/dog_breed_resources/ready_data/dog_breed_ready/dog_breed_ready/test_image_id.npy')

In [34]:
print("************* 1 row of x_train *************")
print(x_train[1,])
print("************* 1 row of y_train *************")
print(y_train[1,])
print("************* 1 row of x_val *************")
print(x_val[1,])
print("************* 1 row of y_val *************")
print(y_val[1,])
print("************* 1 row of x_test_data *************")
print(x_test_data[1,])
print("************* 1 row of one_hot_encode_label *************")
print(one_hot_encode_label)   
print("************* 1 row of test_image_ids *************")
print(test_image_ids[1,])          
      
      

************* 1 row of x_train *************
[[[1.         1.         1.        ]
  [1.         1.         1.        ]
  [1.         1.         1.        ]
  ...
  [1.         1.         1.        ]
  [1.         1.         1.        ]
  [0.99607843 0.99607843 0.99607843]]

 [[1.         1.         1.        ]
  [1.         1.         1.        ]
  [1.         1.         1.        ]
  ...
  [1.         1.         1.        ]
  [1.         1.         1.        ]
  [0.99607843 0.99607843 0.99607843]]

 [[1.         1.         1.        ]
  [1.         1.         1.        ]
  [1.         1.         1.        ]
  ...
  [1.         1.         1.        ]
  [1.         1.         1.        ]
  [0.99607843 0.99607843 0.99607843]]

 ...

 [[0.23529412 0.2627451  0.25882354]
  [0.4117647  0.46666667 0.4392157 ]
  [0.23921569 0.32156864 0.26666668]
  ...
  [0.2        0.28235295 0.22352941]
  [0.10196079 0.21568628 0.11764706]
  [0.14509805 0.28627452 0.12156863]]

 [[0.28235295 0.2901961  0.26

create a base model 

In [0]:
from keras.models import Sequential  
from keras.layers import Dense, Dropout 
from keras.layers import Convolution2D 
from keras.layers import MaxPooling2D
from keras.layers import Flatten

model1 = Sequential()

model1.add(Convolution2D (filters = 128, kernel_size = (3,3),padding = 'Same', 
                         activation ='relu', input_shape = (128, 128, 3))) 
model1.add(MaxPooling2D(pool_size=(2,2)))
model1.add(Convolution2D (filters = 128, kernel_size = (3,3),padding = 'Same', 
                         activation ='relu')) 
model1.add(MaxPooling2D(pool_size=(2,2)))

model1.add(Flatten()) 
# fully connected ANN 
model1.add(Dense(256, activation = 'relu')) 
# output layer
model1.add(Dense(120, activation = 'softmax')) 

model1.compile(optimizer = 'adam' , loss = "categorical_crossentropy", metrics=["accuracy"]) 
model1.summary()




_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_7 (Conv2D)            (None, 128, 128, 128)     3584      
_________________________________________________________________
max_pooling2d_7 (MaxPooling2 (None, 64, 64, 128)       0         
_________________________________________________________________
conv2d_8 (Conv2D)            (None, 64, 64, 128)       147584    
_________________________________________________________________
max_pooling2d_8 (MaxPooling2 (None, 32, 32, 128)       0         
_________________________________________________________________
flatten_4 (Flatten)          (None, 131072)            0         
_________________________________________________________________
dense_7 (Dense)              (None, 256)               33554688  
_________________________________________________________________
dense_8 (Dense)              (None, 120)               30840     
Total para

In [0]:
batch_size = 200 
nb_epochs = 10
history = model1.fit(x_train, y_train,
                    batch_size=batch_size,
                    epochs=nb_epochs,
                    verbose=2, 
                    validation_data=(x_val, y_val),
                    initial_epoch=0)

Train on 7155 samples, validate on 3067 samples
Epoch 1/10
 - 31s - loss: 4.8619 - acc: 0.0119 - val_loss: 4.7825 - val_acc: 0.0108
Epoch 2/10
 - 25s - loss: 4.7200 - acc: 0.0193 - val_loss: 4.6992 - val_acc: 0.0179
Epoch 3/10
 - 25s - loss: 4.4163 - acc: 0.0586 - val_loss: 4.6579 - val_acc: 0.0320
Epoch 4/10
 - 25s - loss: 3.6717 - acc: 0.1852 - val_loss: 4.8573 - val_acc: 0.0372
Epoch 5/10
 - 25s - loss: 2.3731 - acc: 0.4425 - val_loss: 5.7621 - val_acc: 0.0430
Epoch 6/10
 - 25s - loss: 1.1069 - acc: 0.7392 - val_loss: 7.0503 - val_acc: 0.0359
Epoch 7/10
 - 25s - loss: 0.3902 - acc: 0.9159 - val_loss: 8.5066 - val_acc: 0.0401
Epoch 8/10
 - 25s - loss: 0.1197 - acc: 0.9809 - val_loss: 9.3959 - val_acc: 0.0401
Epoch 9/10
 - 25s - loss: 0.0632 - acc: 0.9904 - val_loss: 9.8203 - val_acc: 0.0421
Epoch 10/10
 - 25s - loss: 0.0365 - acc: 0.9971 - val_loss: 10.0255 - val_acc: 0.0385


model1 is way overfit since the  trainning accuarcy is 0.99% but validation accuracy is 0.03 . i expect this model won't perfom well


In [0]:
scores = model1.evaluate(x_train, y_train, verbose=0)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

acc: 99.89%


In [0]:
import pandas as pd
results = model1.predict(x_test_data)
prediction = pd.DataFrame(results)
# Set column names to those generated by the one-hot encoding earlier
prediction.columns = one_hot_encode_label
# Insert the column id from the sample_submission at the start of the data frame
se = pd.Series(test_image_ids)
prediction.insert(0, 'id', se)

prediction.to_csv('Drive/dog_breed_resources/ready_data/dog_breed_ready/dog_breed_ready/model1_submission.csv', index=False)

since model1 is overfitting we going to try batch normalization, dropout reduce the number of fitler and experiment with this to find the better combination

In [29]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Activation
from keras.layers.convolutional import Conv2D, MaxPooling2D
from keras.layers.normalization import BatchNormalization
from keras.utils import to_categorical
from keras import backend as K
import time
from keras.optimizers import Adam
from keras import optimizers


model2 = Sequential()
model2.add(Conv2D(32,kernel_size=(3,3),input_shape=(128,128,3)))
model2.add(BatchNormalization())
model2.add(Activation('relu'))
model2.add(Conv2D(32,kernel_size=(3,3)))
model2.add(BatchNormalization())
model2.add(Activation('relu'))
model2.add(MaxPooling2D(2,2))
model2.add(Dropout(0.6))
model2.add(Flatten())
model2.add(Dense(128))
model2.add(BatchNormalization())
model2.add(Activation('relu'))
model2.add(Dropout(0.7))
model2.add(Dense(64))
model2.add(BatchNormalization())
model2.add(Activation('relu'))
model2.add(Dropout(0.8))
model2.add(Dense(120,activation ='softmax'))

model2.compile(optimizer = 'adam' , loss = "categorical_crossentropy", metrics=["accuracy"]) 
model2.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_33 (Conv2D)           (None, 126, 126, 32)      896       
_________________________________________________________________
batch_normalization_42 (Batc (None, 126, 126, 32)      128       
_________________________________________________________________
activation_21 (Activation)   (None, 126, 126, 32)      0         
_________________________________________________________________
conv2d_34 (Conv2D)           (None, 124, 124, 32)      9248      
_________________________________________________________________
batch_normalization_43 (Batc (None, 124, 124, 32)      128       
_________________________________________________________________
activation_22 (Activation)   (None, 124, 124, 32)      0         
_________________________________________________________________
max_pooling2d_15 (MaxPooling (None, 62, 62, 32)        0         
__________

In [30]:
batch_size = 204 
nb_epochs = 35
history = model2.fit(x_train, y_train,
                    batch_size=batch_size,
                    epochs=nb_epochs,
                    verbose=2, 
                    validation_data=(x_val, y_val),
                    initial_epoch=0)

Train on 7155 samples, validate on 3067 samples
Epoch 1/35
 - 22s - loss: 5.4467 - acc: 0.0099 - val_loss: 5.0155 - val_acc: 0.0111
Epoch 2/35
 - 19s - loss: 5.2495 - acc: 0.0096 - val_loss: 4.8558 - val_acc: 0.0127
Epoch 3/35
 - 19s - loss: 5.0653 - acc: 0.0103 - val_loss: 4.8798 - val_acc: 0.0157
Epoch 4/35
 - 19s - loss: 4.9650 - acc: 0.0126 - val_loss: 4.8430 - val_acc: 0.0147
Epoch 5/35
 - 19s - loss: 4.8940 - acc: 0.0144 - val_loss: 4.7766 - val_acc: 0.0150
Epoch 6/35
 - 19s - loss: 4.8568 - acc: 0.0123 - val_loss: 4.7593 - val_acc: 0.0163
Epoch 7/35
 - 19s - loss: 4.8352 - acc: 0.0129 - val_loss: 4.7546 - val_acc: 0.0157
Epoch 8/35
 - 19s - loss: 4.8136 - acc: 0.0148 - val_loss: 4.7481 - val_acc: 0.0173
Epoch 9/35
 - 19s - loss: 4.7888 - acc: 0.0141 - val_loss: 4.7422 - val_acc: 0.0189
Epoch 10/35
 - 19s - loss: 4.7846 - acc: 0.0158 - val_loss: 4.7391 - val_acc: 0.0205
Epoch 11/35
 - 19s - loss: 4.7620 - acc: 0.0157 - val_loss: 4.7341 - val_acc: 0.0228
Epoch 12/35
 - 19s - loss:

 - 19s - loss: 4.4089 - acc: 0.0379 - val_loss: 4.4741 - val_acc: 0.0323
Epoch 35/35
 - 19s - loss: 4.3951 - acc: 0.0421 - val_loss: 4.4926 - val_acc: 0.0352


In [31]:
import pandas as pd
print("********** 1 row of test data ***************")
print(x_test_data[1,])
results = model2.predict(x_test_data)
print("********** 1 row result after predict ***************")
print(results[1,])
prediction = pd.DataFrame(results)
# Set column names to those generated by the one-hot encoding earlier
prediction.columns = one_hot_encode_label
# Insert the column id from the sample_submission at the start of the data frame
se = pd.Series(test_image_ids)
prediction.insert(0, 'id', se)

prediction.to_csv('Drive/dog_breed_resources/ready_data/dog_breed_ready/dog_breed_ready/model2_submission.csv', index=False)

********** 1 row of test data ***************
[[[0.00392157 0.00392157 0.00392157]
  [0.00392157 0.00392157 0.00392157]
  [0.00392157 0.00392157 0.00392157]
  ...
  [0.00392157 0.00392157 0.00392157]
  [0.00392157 0.00392157 0.00392157]
  [0.00392157 0.00392157 0.00392157]]

 [[0.00392157 0.00392157 0.00392157]
  [0.00392157 0.00392157 0.00392157]
  [0.00392157 0.00392157 0.00392157]
  ...
  [0.00392157 0.00392157 0.00392157]
  [0.00392157 0.00392157 0.00392157]
  [0.00392157 0.00392157 0.00392157]]

 [[0.00392157 0.00392157 0.00392157]
  [0.00392157 0.00392157 0.00392157]
  [0.00392157 0.00392157 0.00392157]
  ...
  [0.00392157 0.00392157 0.00392157]
  [0.00392157 0.00392157 0.00392157]
  [0.00392157 0.00392157 0.00392157]]

 ...

 [[0.4117647  0.43137255 0.42352942]
  [0.3372549  0.35686275 0.34901962]
  [0.39607844 0.41568628 0.40784314]
  ...
  [0.3882353  0.42352942 0.43529412]
  [0.36078432 0.39607844 0.40392157]
  [0.40784314 0.41960785 0.42745098]]

 [[0.44313726 0.4627451  0.4